import type { Church } from "@/constants/ChurchTypes";

export type PostType = "announcement" | "event" | "sermon" | "devotional";

export const POST_TYPES: { type: PostType; label: string; plural: string }[] = [
  { type: "announcement", label: "Announcement", plural: "Announcements" },
  { type: "event", label: "Event", plural: "Events" },
  { type: "sermon", label: "Sermon", plural: "Sermons" },
  { type: "devotional", label: "Devotional", plural: "Devotionals" },
];

/** A piece of church content. Fields that don't apply to a type are null. */
export type Post = {
  id: string;
  churchId: string;
  type: PostType;
  title: string;
  body: string;
  /** S3 object key of the attached image, if any. */
  imageKey: string | null;
  /** Short-lived signed URL for `imageKey`, generated by the server. */
  imageUrl: string | null;
  /** Events: ISO date-times. */
  startsAt: string | null;
  endsAt: string | null;
  location: string | null;
  /** Sermons. */
  preacher: string | null;
  /** Sermons: YouTube / audio / video link. */
  mediaUrl: string | null;
  /** Sermons and devotionals. */
  bibleRef: string | null;
  /** Devotionals: the day it's for, as YYYY-MM-DD. */
  date: string | null;
  createdAt: string;
  updatedAt: string;
};

/** Body for creating or updating a post. */
export type PostInput = Omit<Post, "id" | "churchId" | "imageUrl" | "createdAt" | "updatedAt">;

/** A weekly service. `day` is 0 (Sunday) to 6 (Saturday); `time` is 24-hour "HH:mm". */
export type ServiceTime = {
  day: number;
  time: string;
  label: string;
};

export type ChurchFeed = {
  church: Church & { serviceTimes: ServiceTime[] };
  announcements: Post[];
  /** Upcoming events, soonest first. */
  events: Post[];
  sermons: Post[];
  devotionals: Post[];
};

export const WEEKDAYS = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];

/** Churches picked from the map rather than registered in the app have ids like "osm:node:123". */
export function isRegisteredChurchId(id: string | null | undefined): id is string {
  return Boolean(id) && !String(id).startsWith("osm:");
}
